### ISSUE TITLE
Doesn't work: ERROR:  extension "vector" has no installation script nor update path for version "0.7.4" 

### ISSUE THREAD

**Issue by EricBLivingston** [andreiramani/pgvector_pgsql_windows#1]
Followed the instructions
1. extracted all to share/extension
2. executed create extension vector;

Got that error.

**Comment by andreiramani** [comment]
try to restart the pgsql service and then execute query `create extension vector`

**Comment by EricBLivingston** [comment]
No luck. I rebooted to ensure all processes restarted etc. I still get the same error:

ERROR:  extension "vector" has no installation script nor update path for version "0.7.4"

**Comment by EricBLivingston** [comment]
![image](https://github.com/user-attachments/assets/c66457c3-6116-40c3-88f8-6fb921b06829)

Those are the files I unzipped into:
C:\Program Files\PostgreSQL\16\share\extension

**Comment by andreiramani** [comment]
- from the zip file, copy these files to postgres `\lib` folder: vector.control, vector.dll, vector.exp, vector.lib
- restart the pgsql service and then execute query `create extension vector`

**Comment by EricBLivingston** [comment]
Ok, I copied those files, but got the following:

ERROR:  Could not open extension control file "C:/Program Files/PostgreSQL/16/share/extension/vector.control": No such file or directory.extension "vector" is not available 

So, I moved vector.control back to the extension folder.

Sadly, that just got me back to the old error:
ERROR:  extension "vector" has no installation script nor update path for version "0.7.4" 

So now I have vector.dll, vector.exp, and vector.lib in the lib folder, and all the other files in the extension folder.

**Comment by andreiramani** [comment]
> * from the zip file, copy these files to postgres `\lib` folder: vector.control, vector.dll, vector.exp, vector.lib
> 
>     * restart the pgsql service and then execute query `create extension vector`

Those 4 files exist in 2 folders: `\share\extension\` and `\lib`

Just to make sure, check your postgres version. In the past, I am make similar error because there are 2 different version of postgresql running in the same time.

**Comment by andreiramani** [comment]
![location](https://github.com/user-attachments/assets/7553c499-e51b-4c1d-a3f7-9a6e4255186e)

**Comment by EricBLivingston** [comment]
Ok, odd to have to have them in both places, but I have the same setup you have, with the four files in both places and vector.sql also in extension. But I get the same problem. I also checked an only have Postgresql 16 installed and running.

**Comment by EricBLivingston** [comment]
Aha, I figured it out.

I renamed vector.sql to vector--0.7.4.sql to match other scripts in the extension folder, and the command finished successfully!

**Comment by andreiramani** [comment]
> Aha, I figured it out.
> 
> I renamed vector.sql to vector--0.7.4.sql to match other scripts in the extension folder, and the command finished successfully!

nice to hear that ... :)
